### PR TITLE
[Feature] Split Headless Project from Easel.

### PR DESCRIPTION
**Pull request by MrScautHD**
Description
=======

Adding https://github.com/piegfx/Easel/issues/21

TODO
====
- [x] Main Project Split
- [ ] Add Graphic, Audio... in Scene back with the ClientScene (Dont worry they get different names!)
- [ ] Take a look in generel over all (Like Scene Draw...)
- [ ] Fix Scene (ClientScene)
- [ ] Fix SceneManager (ClientSceneManager)
- [ ] Remove Scene InitializeSceneEvent (Can get removed with this new Types!)
- [ ] Do some Tests

### CODE REVIEW

**Comment by aquagoose** [comment]
I've ran a diff against this vs `Easel.Headless` and I have no idea what the purpose of this PR is. You have reincluded all the graphical stuff, removed entities(!!??), and this project seems to serve no purpose in any chain whatsoever.

This seems to only add confusion and doesn't add anything of much purpose. I have no idea how this is trying to solve any problem.

**Comment by MrScautHD** [comment]
> 

grafik
You know this thing, maybe is it not that simple i thought... let me check it.

**Comment by aquagoose** [comment]
This does not solve that problem in any capacity. It just adds to the problem.

**Comment by MrScautHD** [comment]
grafik
I mean it would fix the issue with overlapping but yea if you take a look in the Easel Project it is marked red.

But the idea that i had works fine...

**Comment by MrScautHD** [comment]
I mean it would work,  but yea it looks a bit wierd. even that it get marked red in your Project (Easel)

**Comment by aquagoose** [comment]
This adds an extra unnecessary project into the works. To solve this issue Easel needs a bit of a redesign. I will not be merging it in this state as it only adds to the problem.

**Comment by MrScautHD** [comment]
> 

well i mean you way is the best :)

**Comment by MrScautHD** [comment]
You right this solution is disgusing, i wanna try out https://github.com/piegfx/Easel/issues/21

**Comment by MrScautHD** [comment]
We need a Solution
============

I saw your todo in the Camera.Headless class, what you think about add a event that everytime get called a Scene Initialize.
So we can check on the Client side (Easel) if the event get called and add Camera + DirectionLight

What you think about this Solution?

**Comment by MrScautHD** [comment]
Note:
====
Client use normally just Easel + Common (because they real diffrent projects give it no conflicts)
Common use Easel.Headless
Server use Common

**Comment by MrScautHD** [comment]
I added now the InitializeSceneEvent, if you has any other Solution let me know!

**Comment by MrScautHD** [comment]
"eg. Create an Easel.Common project with an IEaselGame. Then implement that in both Easel.Headless and Easel (I'd probably rename this to reflect it has rendering).
Then create Stellution.Client and Stellution.Server as new projects. You can take the dependency on the correct headless-or-not library. Everything can work with IEaselGame because that part is common. "

We need to impliment something like this...

**Comment by aquagoose** [comment]
You seem to be going around in circles and this is not the way I want this to work so I am going to close this.

**Comment by MrScautHD** [comment]
> You seem to be going around in circles and this is not the way I want this to work so I am going to close this.

understandable, well yea a Variable like before in GameSettings would make more sence at all.

**Pull request closed without merging**
